### ISSUE TITLE
This error on windows

### ISSUE THREAD

**Issue by Explorer017** [JakeyGilly/CompactifierPlusPlus#2]
`global.cpp:44:58: error: cannot convert 'std::__cxx11::basic_string<char>::iterator' {aka '__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >'} to 'const char*'`

**Comment by JakeyGilly** [comment]
dont use windows

**Comment by Explorer017** [comment]
no

**Comment by Explorer017** [comment]
# how bout no
![https://img.shields.io/badge/just%20make%20it-work-green](https://img.shields.io/badge/just%20make%20it-work-green)

**Comment by JakeyGilly** [comment]
only avalible on CLANG
![CLANG](https://img.shields.io/badge/CLANG-YES-green.png)
![G++](https://img.shields.io/badge/G%2B%2B-NO-red.png)
