### ISSUE TITLE
Multiline comments longer than 1 line dont work properly

### ISSUE THREAD

**Issue by Explorer017** [JakeyGilly/CompactifierPlusPlus#4]
# Multiline comments longer than 1 line dont work properly

Multiline comments longer than 1 line add the second line to the file, and if it is 3 lines or more, it causes a segmentation fault.

code tested with:
```py
"""
line 1
line 2
line 3
"""
```

result:
```
Opened File a.py
Type .py
File size: 32 Bytes
Segmentation fault
```

(using wsl and g++ on windows)

**Comment by JakeyGilly** [comment]
okay dokie

**Comment by JakeyGilly** [comment]
Fixed in latest commit 👍
[61def799f77aeb07a1c5cad5cd296d74fc9ca2c3](https://github.com/JakeyGilly/CompactifierPlusPlus/commit/61def799f77aeb07a1c5cad5cd296d74fc9ca2c3)
